### ISSUE TITLE
Error when opening system, settings and groups on the side menu.

### ISSUE THREAD

**Issue by Lukas8299** [revenz/Fenrus#9]
Error when opening system, settings, groups on the side menu.

```ReferenceError: /app/views/settings.ejs:1
 >> 1| <%- include('./partials/head.ejs' ) %>
    2| 
    3| <link rel="stylesheet" href="/css/settings.min.css?version=<%= version %>" />
    4| <link rel="stylesheet" href="/css/toggle-switchy.css" />

/app/views/partials/head.ejs:12
    10|         <title>Fenrus</title>
    11|     <% } %>
 >> 12|     <link rel="stylesheet" href="/css/site.min.css?version=<%= version %>" />
    13|     <link id="theme-style" rel="stylesheet" href="/themes/<%= settings.Theme || 'Default' %>/theme.min.css?version=<%= version %>" />
    14| 
    15|     <% 

version is not defined
    at eval ("/app/views/partials/head.ejs":24:26)
    at head (/app/node_modules/ejs/lib/ejs.js:692:17)
    at include (/app/node_modules/ejs/lib/ejs.js:690:39)
    at eval ("/app/views/settings.ejs":10:17)
    at settings (/app/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/app/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/app/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/app/node_modules/express/lib/view.js:135:8)
    at tryRender (/app/node_modules/express/lib/application.js:640:10)
    at Function.render (/app/node_modules/express/lib/application.js:592:3)```

**Comment by revenz** [comment]
thanks, fixed in version "0.1.0.110" just update your docker.
